### ISSUE TITLE
Can we switch from QWERTY To AZERTY keyboard ?

### ISSUE THREAD

**Issue by maroodb** [agirorn/node-hid-stream#16] opened 2020-02-29 23:40 UTC
is it possible to choose keyboard mode ?

**Comment by agirorn** [comment] 2020-03-03 08:27
I'm not sure what you mean.

If you are referring to configuring a barcode scanner to be in keyboard mode then that should be possible by scanning a few barcodes from the barcodes canners manual.

**Comment by maroodb** [comment] 2020-03-03 10:06
> 
> 
> I'm not sure what you mean.
> 
> If you are referring to configuring a barcode scanner to be in keyboard mode then that should be possible by scanning a few barcodes from the barcodes canners manual.

I already configured the barecode scanner, when I use it directly (without the library) it works fine, the problem is that the library convert input to QWERTY map

**Comment by agirorn** [comment] 2020-03-04 08:50
1. When you say it works fine do you mean "You plugin the barcode scanner then open a text editor and scan a barcode and that barcode gets typed into the text editor"?

If that is the case then you still might need to configure the barcodes scanner.


2. When you say QWERTY map you are referring to getting this kind of data then it is working as expected.

```
{  // HidKeyboardPacket
  modifiers: {
    leftShift: false,
    leftControl: true,
    leftAlt: true,
    leftMeta: false,
    rightCtrl: false,
    rightShift: false,
    rightAlt: false,
    rightMeta: false
  },
  keyCodes: [ 76 ],
  keyChars: [],
  errorStatus: false
}
```

If this is not the desired output for you then you might want to use the KeyboardCharacters KeyboardLines.

If you want to get a single data call for each barcode scanned I recommend you use the [KeyboardLines](https://github.com/agirorn/node-hid-stream/blob/master/examples/honeywell-voyager-1450g/read-keyboard-lines.js) since it splits the stream of data on each new line char ('/\r?\n/') detected in the stream of data. for this to work with your scanner you probably need to configure the scanner to add the new line character at the end of each scan and that is done by scanner the correct configuration barcode.

**Comment by maroodb** [comment] 2020-03-13 22:00
Hello Again, I have the first case, but why configure the scanner when it works with the text editor ?, do you mean I have to configure it as QWERTY ?

**Comment by agirorn** [comment] 2020-07-16 11:27
I'm closing this issues since I don't think node-hid-stream has anything to do with the type of keyboard. The issue is probably that the scanner ins configured as a keyboard on the computer and not as raw HID device and the module can not read from it. I suggest you look at the manufacturer's documentation for further configuration.

**Closed as completed by agirorn** 2020-07-16 11:27 UTC
